# Generated by Django 2.2.2 on 2019-06-10 07:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('object1', django.db.models.manager.Manager()),
            ],
        ),
    ]
