# Generated by Django 2.2.2 on 2019-06-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20190610_1526'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
            ],
        ),
    ]
