# Generated by Django 2.2.2 on 2019-06-10 09:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20190610_1711'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
