# Generated by Django 2.2.2 on 2019-06-20 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Crow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crow', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.ImageField(upload_to='')),
                ('pic2', models.ImageField(upload_to='')),
                ('pic3', models.ImageField(upload_to='')),
                ('pic4', models.ImageField(upload_to='')),
                ('pic5', models.ImageField(upload_to='')),
                ('desc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_price', models.IntegerField()),
                ('goods_size', models.IntegerField()),
                ('goods_info', models.TextField(max_length=300)),
                ('goods_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Brand')),
                ('goods_crow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Crow')),
                ('goods_pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Pic')),
                ('goods_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.Style')),
            ],
        ),
        migrations.AddField(
            model_name='crow',
            name='crow_style',
            field=models.ManyToManyField(to='shopping.Style'),
        ),
    ]
